#
# This file contains configuration flags to customize your site
#

title: Intelligent Systems and Operations in Aviation
description: Research Group at the ZHAW Institute of Data Analysis and Process Design, led by Dr. Manuel Renold
show_downloads: true
theme: jekyll-theme-cayman


# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 
favicon: 

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: IntelligentSystemsGroup
  instagram:
  linkedin: 
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: 


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: https-isandaiinaviation-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-HPTPVQ5P7P

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: 

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# show blog posts with dates in the future
future: true

#to allow UTF-8 encodings
encoding: utf-8

#generate excerpts automatically (added 2020-10-08)
page_excerpts: true
excerpt_separator: <!-- more -->